### ISSUE TITLE
Balrogadmin should return 401 instead 500 on AuthError

### ISSUE THREAD

**Issue by allan-silva** [mozilla-releng/balrog#2605]
![image](https://user-images.githubusercontent.com/9947646/181916124-1ba9b2c2-7ec6-4ddb-afe3-99cc6265b61d.png)

```
balrog-balrogadmin-1  | 2022-07-30 13:02:29,525 - ERROR - PID: 11 - Request: 140355487237408 - auslib.web.admin.base.ise#140: Caught ISE 500 error: AuthError({'code': 'authorization_header_missing', 'description': 'Authorization header is expected'}, 401)
balrog-balrogadmin-1  | Traceback (most recent call last):
balrog-balrogadmin-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
balrog-balrogadmin-1  |     rv = self.dispatch_request()
balrog-balrogadmin-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
balrog-balrogadmin-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
balrog-balrogadmin-1  |   File "/usr/local/lib/python3.9/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
balrog-balrogadmin-1  |     response = function(request)
balrog-balrogadmin-1  |   File "/usr/local/lib/python3.9/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
balrog-balrogadmin-1  |     response = function(request)
balrog-balrogadmin-1  |   File "/usr/local/lib/python3.9/site-packages/connexion/decorators/validation.py", line 193, in wrapper
balrog-balrogadmin-1  |     response = function(request)
balrog-balrogadmin-1  |   File "/usr/local/lib/python3.9/site-packages/connexion/decorators/validation.py", line 396, in wrapper
balrog-balrogadmin-1  |     return function(request)
balrog-balrogadmin-1  |   File "/usr/local/lib/python3.9/site-packages/connexion/decorators/parameter.py", line 116, in wrapper
balrog-balrogadmin-1  |     return function(**kwargs)
balrog-balrogadmin-1  |   File "/app/src/auslib/web/admin/views/base.py", line 17, in decorated
balrog-balrogadmin-1  |     username = verified_userinfo(request, app.config["AUTH_DOMAIN"], app.config["AUTH_AUDIENCE"])["email"]
balrog-balrogadmin-1  |   File "/app/src/auslib/util/auth.py", line 58, in verified_userinfo
balrog-balrogadmin-1  |     access_token = get_access_token(request)
balrog-balrogadmin-1  |   File "/app/src/auslib/util/auth.py", line 26, in get_access_token
balrog-balrogadmin-1  |     raise AuthError({"code": "authorization_header_missing", "description": "Authorization header is expected"}, 401)
balrog-balrogadmin-1  | auslib.util.auth.AuthError: ({'code': 'authorization_header_missing', 'description': 'Authorization header is expected'}, 401)
balrog-balrogadmin-1  | [pid: 11|app: 0|req: 115/115] 172.20.0.6 () {48 vars in 741 bytes} [Sat Jul 30 13:02:28 2022] POST /api/emergency_shutoff => generated 107 bytes in 753 msecs (HTTP/1.1 500) 10 headers in 439 bytes (1 switches on core 0)
```

**Comment by MelakuAlehegn** [comment]
Can I pick this issue @gabrielBusta @bhearsum @allan-silva . Confirming if the issue still exists.

**Comment by bhearsum** [comment]
> Can I pick this issue @gabrielBusta @bhearsum @allan-silva . Confirming if the issue still exists.

Sure - but FYI, this is a backend issue, not a frontend one.

**Comment by MelakuAlehegn** [comment]
> > Can I pick this issue @gabrielBusta @bhearsum @allan-silva . Confirming if the issue still exists.
> 
> Sure - but FYI, this is a backend issue, not a frontend one.

Ok. Thanks for the info @bhearsum
